env:
  global: 
    - NSS_DEFAULT_DB_TYPE="sql"
    - I_DONT_MIND_IF_MY_CHROME_PKI_DATABASE_GETS_DELETED=true
    - secure: "AgFID7Zfh65cwfqveYJXUT8q7xcBDA6+gNCmV90ihmvips5Uxrb7aGHQYVxPPGQy1pbv2fMnxWHjj5HR7gVp9W06HhN6kTqseGYABPWk0Tmyd0rNdDcvSMfXx9yy4jc+f2tqdmMcNOhdJ+feBaFq7uZOkqlTndkdD8m1XBMZUVs="
before_install:
- ./tools/setupdoc
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cp /etc/apt/sources.list /tmp
- echo deb http://de.archive.ubuntu.com/ubuntu/ trusty main restricted universe >/tmp/sources.list
- echo deb http://de.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe >>/tmp/sources.list
- sudo cp /tmp/sources.list /etc/apt
- cp /etc/hosts /tmp
- echo "127.0.0.1 local.sso.edemokraciagep.org" >>/tmp/hosts
- sudo cp /tmp/hosts /etc/hosts
- sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32 40976EAF437D05B5
- sudo apt-get --purge remove postgresql-common
- sudo apt-get update
- sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" --force-yes -fuy upgrade
- sudo apt-get -y install python make python-pip firefox openjdk-7-jre curl docbook-xsl apache2 libapache2-mod-wsgi swig chromium-browser chromium-chromedriver libnss3-tools
- sudo cp src/integrationtest/certs.json /etc/chromium-browser/policies/managed/
- dpkg -l '*chrom*'
- dpkg -L chromium-browser
- dpkg -L chromium-chromedriver
- sudo pip install -r requirements.txt
script:
- make checkall
- ./tools/commitdocs
