before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- cp /etc/hosts /tmp
- echo ""127.0.0.1 local.sso.edemokraciagep.org" >>/tmp/hosts
- sudo cp /tmp/hosts /etc/hosts
- sudo apt-get update
- sudo apt-get install python make python-pip firefox openjdk-7-jre curl docbook-xsl
- sudo pip install -r requirements.txt
script:
- make
