env:
  global:
    secure: "AgFID7Zfh65cwfqveYJXUT8q7xcBDA6+gNCmV90ihmvips5Uxrb7aGHQYVxPPGQy1pbv2fMnxWHjj5HR7gVp9W06HhN6kTqseGYABPWk0Tmyd0rNdDcvSMfXx9yy4jc+f2tqdmMcNOhdJ+feBaFq7uZOkqlTndkdD8m1XBMZUVs="
before_install:
- ./tools/setupdoc
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cp /etc/apt/sources.list /tmp
- echo deb http://de.archive.ubuntu.com/ubuntu/ trusty main restricted universe >/tmp/sources.list
- sudo cp /tmp/sources.list /etc/apt
- cp /etc/hosts /tmp
- echo "127.0.0.1 local.sso.edemokraciagep.org" >>/tmp/hosts
- sudo cp /tmp/hosts /etc/hosts
- sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
- sudo apt-get update
- sudo DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
- sudo apt-get -y install python make python-pip firefox openjdk-7-jre curl docbook-xsl apache2 libapache2-mod-wsgi
- sudo pip install -r requirements.txt
script:
- make checkall
- ./tools/commitdocs
